apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.name }}-deployment"
  labels:
    app: "{{ .Values.name }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Values.name }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.name }}"
    spec:
      containers:
      - name: "{{ .Values.container.name }}"
        image: "{{ .Values.container.image }}"
        ports:
        - containerPort: {{ .Values.container.port }}
        livenessProbe:
          httpGet:
            path: /healthy
            port: {{ .Values.container.port }}
            httpHeaders:
            - name: X-Health
              value: Awesome
          initialDelaySeconds: 30
          periodSeconds: 1