apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.service.name }}"
spec:
  type: NodePort
  selector:
    app: "{{ .Values.service.name }}"
  ports:
    - name: app
      protocol: TCP
      port: 80
