apiVersion: apps/v1
kind: Deployment
metadata:
  name: microserver-deployment
  labels:
    app: microserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microserver
  template:
    metadata:
      labels:
        app: microserver
    spec:
      containers:
      - name: erlc
        image: 487533102028.dkr.ecr.us-east-1.amazonaws.com/erlc
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthy
            port: 8080
            httpHeaders:
            - name: X-Health
              value: Awesome
          initialDelaySeconds: 30
          periodSeconds: 3
      imagePullSecrets:
      - name: awsecr-cred