apiVersion: apps/v1
kind: Deployment
metadata:
  name: microserver-deployment
  labels:
    app: microserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microserver
  template:
    metadata:
      labels:
        app: microserver
    spec:
      containers:
      - name: erlc
        image: erlc
        imagePullPolicy: Never
        ports:
        - containerPort: 8080