apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: microserver-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  backend:
    serviceName: default-microserver-service
    servicePort: 80
  rules:
  - host: microserver.erlang
    http:
      paths:
      - path: /
        backend:
          serviceName: microserver
          servicePort: 8080